### ISSUE TITLE
Protocolize causes a ClassCastException with Geyser-BungeeCord in certain cases

### ISSUE THREAD

**Issue by Camotoy** [Exceptionflug/protocolize#107]
See also: https://github.com/GeyserMC/Geyser/issues/2640

Tested Waterfall versions: 450, 454

Tested Protocolize version: commit 88c189f35a820cddd6d40baea7d032361ad22f26 compiled locally.

Tested Geyser version: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/931/

To reproduce: install both Protocolize and Geyser-BungeeCord on the server, and ensure the `passthrough-motd` setting is enabled in Geyser.

Error: 
```
[22:57:42 WARN]: Error dispatching event ProxyPingEvent(connection=org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough$GeyserPendingConnection@a2ccd3b, response=ServerPing(version=ServerPing.Protocol(name=Waterfall 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, protocol=756), players=ServerPing.Players(max=1, online=0, sample=null), description=Another Bungee server2, modinfo=ServerPing.ModInfo(type=FML, modList=[]))) to listener dev.simplix.protocolize.bungee.listener.PlayerListener@4fc2933e
java.lang.ClassCastException: class org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough$GeyserPendingConnection cannot be cast to class net.md_5.bungee.protocol.AbstractPacketHandler (org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough$GeyserPendingConnection is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @7cf162bc; net.md_5.bungee.protocol.AbstractPacketHandler is in unnamed module of loader 'app')
	at dev.simplix.protocolize.bungee.listener.PlayerListener.onPing(PlayerListener.java:27) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor21.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:48) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at org.geysermc.platform.bungeecord.GeyserBungeePingPassthrough.getPingInformation(GeyserBungeePingPassthrough.java:54) ~[?:?]
	at org.geysermc.connector.network.ConnectorServerEventHandler.onQuery(ConnectorServerEventHandler.java:100) ~[?:?]
	at com.nukkitx.protocol.bedrock.BedrockServer$BedrockServerListener.onQuery(BedrockServer.java:93) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer.onUnconnectedPing(RakNetServer.java:239) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer.access$400(RakNetServer.java:34) ~[?:?]
	at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:366) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:616) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:651) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:56) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:490) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-454.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:aba3aff:454]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

Problem code: Geyser calls a fake `ProxyPingEvent` to gather ping about the server: https://github.com/GeyserMC/Geyser/blob/master/bootstrap/bungeecord/src/main/java/org/geysermc/platform/bungeecord/GeyserBungeePingPassthrough.java#L54 .
Protocolize assumes all `ProxyPingEvent`s implement AbstractPacketHandler: https://github.com/Exceptionflug/protocolize/blob/master/protocolize-bungeecord/src/main/java/dev/simplix/protocolize/bungee/listener/PlayerListener.java#L27 .

Cheers.

**Comment by Exceptionflug** [comment]
Hello, this is already known to us. Currently only the protocolize velocity implementation supports the usage of Geyser. There is currently no ETA on when Geyser will be supported on BungeeCord.

**Comment by Camotoy** [comment]
Geyser works fine with Protocolize, to be clear. I tested with the same development build and https://www.spigotmc.org/resources/bungee-command-blocker.93180/ - the only issue is that in the link I provided in the issue, Protocolize assumes all connections from ProxyPingEvent extend AbstractPacketHandler. Not necessarily Geyser doing network hacks; just a weird use of API.

**Comment by Exceptionflug** [comment]
Vanilla BungeeCord will always return an instance of AbstracktPacketHandler at this point.

**Comment by ChiboYen** [comment]
Protocolize V2: https://ci.exceptionflug.de/job/Protocolize2/146/
Geyser: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/master/997/
Velocity: 3.1.2

A similar thing happens on Velocity, just putting it here in case it's related to this issue.
```
[00:18:50 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Unable to initialize InboundConnection on ping
java.lang.UnsupportedOperationException: InboundConnection of type org.geysermc.geyser.platform.velocity.GeyserVelocityPingPassthrough$GeyserInboundConnection is not supported. Protocolize will not work properly. Please check for incompatible plugins.
        at dev.simplix.protocolize.velocity.listener.PlayerListener.initConnection(PlayerListener.java:93) ~[?:?]
        at dev.simplix.protocolize.velocity.listener.PlayerListener.onPing(PlayerListener.java:61) ~[?:?]
        at dev.simplix.protocolize.velocity.listener.Lmbda$551.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Exceptionflug** [comment]
Hey, sorry for the late response. Support for Geyser has been improved during the last releases. Can you try again using the latest version?

**Comment by ChiboYen** [comment]
Yes, sorry for the late reply, I am on the latest build now and the error is still happening:
```
[07:15:11 ERROR] [dev.simplix.protocolize.velocity.listener.PlayerListener]: Unable to initialize InboundConnection on ping
java.lang.UnsupportedOperationException: InboundConnection of type org.geysermc.geyser.platform.velocity.GeyserVelocityPingPassthrough$GeyserInboundConnection is not supported. Protocolize will not work properly. Please check for incompatible plugins.
        at dev.simplix.protocolize.velocity.listener.PlayerListener.initConnection(PlayerListener.java:93) ~[?:?]
        at dev.simplix.protocolize.velocity.listener.PlayerListener.onPing(PlayerListener.java:61) ~[?:?]
        at dev.simplix.protocolize.velocity.listener.Lmbda$554.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-b8f1df44-b110)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Exceptionflug** [comment]
This was not the latest version on the date you posted. Please download the latest version from here: https://ci.exceptionflug.de/job/Protocolize2/lastSuccessfulBuild/artifact/protocolize-velocity/target/protocolize-velocity.jar

And please tell me if it is fixed.

**Comment by ChiboYen** [comment]
Yes, sorry, we talked on the Discord, I am now on the latest build and it is now fixed.

**Comment by patyhank** [comment]
```[16:52:45 WARN]: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=patyhank, receiver=net.md_5.bungee.ServerConnection@1b696c2e), cancelled=false, tag=floodgate:skin) to listener org.geysermc.floodgate.pluginmessage.BungeePluginMessageUtils@49faf066
java.lang.NullPointerException: Cannot invoke "java.util.UUID.getMostSignificantBits()" because "uuid" is null```
