### ISSUE TITLE
Duplicate handler name error

### ISSUE THREAD

**Issue by dobrac** [Exceptionflug/protocolize#119]
**Describe the bug**
Duplicate handler name error occurs when many people try to join the proxy, but their loginevent is cancelled.

**To Reproduce**
Try to connect many accounts (like a botnet) which loginevent is cancelled to a server and the error occurs.

**Expected behavior**
No error is written to the console

**Log (exception)**
```
Exception occurred while injecting into netty pipeline
java.lang.IllegalArgumentException: Duplicate handler name: protocolize2-encoder
	at io.netty.channel.DefaultChannelPipeline.checkDuplicateName(DefaultChannelPipeline.java:1055) ~[server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.DefaultChannelPipeline.filterName(DefaultChannelPipeline.java:284) ~[server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:301) ~[server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.DefaultChannelPipeline.addAfter(DefaultChannelPipeline.java:290) ~[server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at dev.simplix.protocolize.bungee.netty.NettyPipelineInjector.injectAfter(NettyPipelineInjector.java:36) [protocolize-bungeecord.jar:?]
	at dev.simplix.protocolize.bungee.listener.PlayerListener.onPreLogin(PlayerListener.java:43) [protocolize-bungeecord.jar:?]
	at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_292]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_292]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:49) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at bungeepluginmanager.ModifiedPluginEventBus.post(ModifiedPluginEventBus.java:38) [BungeePluginManager.jar:?]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:412) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:406) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:35) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:514) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [server.jar:git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:7e47490:1633]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Proxy environment**
BungeeCord build 1633

**Minecraft versions used**
Unknown client version, server version is 1.8.9

**Comment by Exceptionflug** [comment]
This should not be possible. Can you send a list of installed proxy plugins?

**Comment by Exceptionflug** [comment]
There is no response anymore. Please open a new issue if there is still interest.
