### ISSUE TITLE
Disconnect when clicking on backpack item

### ISSUE THREAD

**Issue by hhhfsj** [Exceptionflug/protocolize#123]
**Describe the bug**
Disconnect when clicking on backpack item

**To Reproduce**
Click on backpack items

**Expected behavior**

`
[22:33:15 INFO]: [connected player] fsj (/192.168.1.1:13793) has disconnected: 您的连接发生内部错误。
[22:33:15 ERROR]: [connected player] fsj (/192.168.1.1:13793): exception encountered in com.velocitypowered.proxy.connection.client.ClientPlaySessionHandler@751ffbdb
io.netty.handler.codec.CorruptedFrameException: Packet sent for class dev.simplix.protocolize.velocity.packets.GeneratedClickWindowWrapper was too big (expected 14 bytes, got 22 bytes)
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleOverflow(MinecraftDecoder.java:109) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:87) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2.jar:3.1.2-SNAPSHOT (git-95a32ad4-b128)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
`

**Proxy environment**
Velocity: 3.1.2

**Minecraft versions used**
Minecraft: 1.16.5
Fabric Loader: 0.13.3
Modpacks: All of Fabric 3 2.8.8

**Comment by Exceptionflug** [comment]
Hello, I am assuming, that you are running a modded minecraft server? Mods are not supported by protocolize.

**Comment by hhhfsj** [comment]
Any plan to support modded minecraft server?

**Comment by Exceptionflug** [comment]
No
