### ISSUE TITLE
Not working on Velocity 1.19

### ISSUE THREAD

**Issue by Pantera07** [Exceptionflug/protocolize#129]
**Describe the bug**
1.19 Client players cannot connect.
And if I delete this plugin, it connects fine.

**To Reproduce**
1. Use the latest Velocity that supports 1.19.

**Expected behavior**
Players should be able to connect.

**Screenshots**
![화면 캡처 2022-06-08 135814](https://user-images.githubusercontent.com/89838384/172538647-eafd5ca3-5ab5-4964-ab2d-f5b2bd727517.png)
![dontsupport](https://user-images.githubusercontent.com/89838384/172538879-283e4c12-98ae-41b8-89f8-a99dde9812a8.png)

**Proxy environment**
Velocity #147

**Minecraft versions used**
1.18.2 Paper (with ViaVersion)
1.19 Vanilla Client

**Comment by Exceptionflug** [comment]
Hey, please launch Velocity with the VM argument -Devlocity.packet-decode-logging=true and send the log after a player tries to connect with 1.19.

**Comment by Pantera07** [comment]
> Hey, please launch Velocity with the VM argument -Devlocity.packet-decode-logging=true and send the log after a player tries to connect with 1.19.
```
[17:07:13] [main/INFO]: Booting up Velocity 3.1.2-SNAPSHOT (git-4b1cdbcb-b147)...
[17:07:13] [main/INFO]: Loading localizations...
[17:07:13] [main/INFO]: Connections will use NIO channels, Java compression, Java ciphers
[17:07:13] [main/INFO]: Loading plugins...
[17:07:13] [main/INFO]: Loaded plugin protocolize v2 by Exceptionflug
[17:07:13] [main/INFO]: Loaded 1 plugins
[17:07:13] [Velocity Async Event Executor - #0/INFO]: ======= PROTOCOLIZE =======
[17:07:13] [Velocity Async Event Executor - #0/INFO]: Version 2.2.0:315 by Exceptionflug
[17:07:13] [Velocity Async Event Executor - #0/INFO]: Swap channel initializers (ignore the following two warnings)...
[17:07:13] [Velocity Async Event Executor - #0/INFO]: Respecting the previous registered BackendChannelInitializer: com.velocitypowered.proxy.network.BackendChannelInitializer
[17:07:13] [Velocity Async Event Executor - #0/WARN]: The backend channel initializer has been replaced by dev.simplix.protocolize.velocity.ProtocolizePlugin.swapChannelInitializers(ProtocolizePlugin.java:133)
[17:07:13] [Velocity Async Event Executor - #0/INFO]: Respecting the previous registered ServerChannelInitializer: com.velocitypowered.proxy.network.ServerChannelInitializer
[17:07:13] [Velocity Async Event Executor - #0/WARN]: The server channel initializer has been replaced by dev.simplix.protocolize.velocity.ProtocolizePlugin.swapChannelInitializers(ProtocolizePlugin.java:135)
[17:07:13] [Velocity Async Event Executor - #0/INFO]: Swapped channel initializers
[17:07:14] [Velocity Async Event Executor - #0/INFO]: Enabled module dev.simplix.protocolize.data.DataModule
[17:07:14] [Netty NIO Boss #0/INFO]: Listening on /[0:0:0:0:0:0:0:0]:25565
[17:07:14] [main/INFO]: Done (1.99s)!
[17:07:16] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10449) has connected
[17:07:16] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has connected
[17:07:17] [Netty NIO Worker #1/ERROR]: [server connection] Mad_Daniel -> lobby: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@7721faef
io.netty.handler.codec.CorruptedFrameException: Packet sent for class dev.simplix.protocolize.velocity.packets.GeneratedHeldItemChangeWrapper was too big (expected 3 bytes, got 4 bytes)
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleOverflow(MinecraftDecoder.java:109) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:87) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT-147.jar:3.1.2-SNAPSHOT (git-4b1cdbcb-b147)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:07:17] [Netty NIO Worker #1/INFO]: [connected player] Mad_Daniel (/127.0.0.1:10449) has disconnected: lobby 에 연결하던 도중 문제가 발생했습니다.
[17:07:17] [Netty NIO Worker #1/INFO]: [server connection] Mad_Daniel -> lobby has disconnected
```

**Comment by Exceptionflug** [comment]
Will be resolved in https://github.com/Exceptionflug/protocolize/issues/130
