### ISSUE TITLE
 1.19 trade offers error

### ISSUE THREAD

**Issue by Pantera07** [Exceptionflug/protocolize#131]
**Describe the bug**
An error occurs when a player clicks on trade offers.
And if I remove this plugin, it works fine.

**To Reproduce**
1. Open the server.
2. Connect to the 1.19 version client.
3. Click on villager trade offers.

**Screenshots**
![bug](https://user-images.githubusercontent.com/89838384/173171026-425dc422-dc80-4679-bff0-b7dab6dc2498.png)
```
[12:48:08] [Netty NIO Worker #2/ERROR]: Unable to write dump file Sat-Jun-11-12:48:08-KST-2022.zip
java.io.FileNotFoundException: Invalid file path
	at java.io.FileOutputStream.<init>(FileOutputStream.java:229) ~[?:?]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:184) ~[?:?]
	at dev.simplix.protocolize.api.util.DebugUtil.writeDump(DebugUtil.java:39) ~[?:?]
	at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.decode(VelocityProtocolizePacket.java:59) ~[?:?]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-3.1.2-SNAPSHOT.jar:3.1.2-SNAPSHOT (git-74edac96-b153)]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[12:48:08] [Netty NIO Worker #2/ERROR]: === EXCEPTION CAUGHT IN DECODER ===
[12:48:08] [Netty NIO Worker #2/ERROR]: Protocolize 2.2.1:317
[12:48:08] [Netty NIO Worker #2/ERROR]: Stream Direction: UPSTREAM
[12:48:08] [Netty NIO Worker #2/ERROR]: InboundConnection: [connected player] Mad_Daniel (/127.0.0.1:1408), ServerConnection: null
[12:48:08] [Netty NIO Worker #2/ERROR]: Protocol version: 1.19
[12:48:08] [Netty NIO Worker #2/ERROR]: io.netty.handler.codec.CorruptedFrameException: Error decoding class dev.simplix.protocolize.velocity.packets.GeneratedHeldItemChangeWrapper Direction SERVERBOUND Protocol 1.19 State PLAY ID 25
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:48:08] [Netty NIO Worker #2/ERROR]: Caused by: io.netty.handler.codec.CorruptedFrameException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.HeldItemChange at protocol version 1.19 in direction SERVERBOUND
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.decode(VelocityProtocolizePacket.java:58)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	... 34 more
[12:48:08] [Netty NIO Worker #2/ERROR]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(2) exceeds writerIndex(3): UnpooledSlicedByteBuf(ridx: 2, widx: 3, cap: 3/3, unwrapped: PooledUnsafeHeapByteBuf(ridx: 0, widx: 4, cap: 4))
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at dev.simplix.protocolize.data.packets.HeldItemChange.read(HeldItemChange.java:58)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.decode(VelocityProtocolizePacket.java:49)
[12:48:08] [Netty NIO Worker #2/ERROR]: 	... 35 more
```

**Proxy environment**
Velocity #153

**Minecraft versions used**
Server: (1.18.2 Paper + Latest ViaVersion) or (1.19 Paper)
```
Latest ViaVersion: https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/
1.19 Paper: https://files.eim.one/paper-1.19-experimental-6.jar
```
Client: 1.19 Vanilla

**Comment by spartan090907** [comment]
I have had the same issue. when i use purpur 1.18.2 and Viaversion and a bedrock 1.19 client or java 1.19 client trades

**Comment by Pantera07** [comment]
https://github.com/Exceptionflug/protocolize-data/commit/5c750604dbb9c3fe4094bb3155af2d72ce71d8d4
This issue has been resolved.

https://ci.exceptionflug.de/job/Protocolize2/lastSuccessfulBuild/
