### ISSUE TITLE
BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.HeldItemChange at protocol version 759 in direction TO_SERVER

### ISSUE THREAD

**Issue by mibby** [Exceptionflug/protocolize#135]
**Describe the bug**
```
[20:56:42] [Netty Worker IO Thread #12/ERROR] [dev.simplix.protocolize.api.util.DebugUtil]: Unable to write dump file Fri-Jun-17-20:56:42-PDT-2022.zip
java.io.IOException: Stream closed
	at java.util.zip.ZipOutputStream.ensureOpen(ZipOutputStream.java:97) ~[?:?]
	at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:261) ~[?:?]
	at dev.simplix.protocolize.api.util.DebugUtil.writeDump(DebugUtil.java:45) ~[?:?]
	at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:57) ~[?:?]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:ab3ccb8:496]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:56:42] [Netty Worker IO Thread #12/ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[20:56:42] [Netty Worker IO Thread #12/ERROR]: [Protocolize] Protocolize 2.2.1:317
[20:56:42] [Netty Worker IO Thread #12/ERROR]: [Protocolize] Stream Direction: UPSTREAM
[20:56:42] [Netty Worker IO Thread #12/ERROR]: [Protocolize] Connection: [/154.21.216.95:62277|rtcabooservb] <-> InitialHandler
[20:56:42] [Netty Worker IO Thread #12/ERROR]: [Protocolize] Protocol version: 759
[20:56:42] [Netty Worker IO Thread #12/ERROR]: io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.HeldItemChange at protocol version 759 in direction TO_SERVER
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: Caused by: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.HeldItemChange at protocol version 759 in direction TO_SERVER
[20:56:42] [Netty Worker IO Thread #12/ERROR]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(2) exceeds writerIndex(3): PooledSlicedByteBuf(ridx: 2, widx: 3, cap: 3/3, unwrapped: PooledUnsafeDirectByteBuf(ridx: 4, widx: 4, cap: 4))
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at dev.simplix.protocolize.data.packets.HeldItemChange.read(HeldItemChange.java:58)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:48)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:56:42] [Netty Worker IO Thread #12/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Proxy environment**
Waterfall dev 496 (BungeeCord Fork)
Protocolize 2.2.1

**Minecraft versions used**
Mixed 1.18.2 & 1.19 clients on a 1.19 server.

**Comment by Exceptionflug** [comment]
Hey, sorry for the late response. Which build version of Protocolize are you using (/protocolize)? Try to download the latest build from our website. This bug should already have been fixed.

**Comment by mibby** [comment]
I was using the latest release on Spigot. Using jenkins dev builds, this issue is resolved since it builds with the fix in the dependency.

**Comment by Exceptionflug** [comment]
The Spigot Download also downloads the latest build from jenkins. But glad that it fixed your problem.
