### ISSUE TITLE
I can't log in to the server

### ISSUE THREAD

**Issue by Ushust** [Exceptionflug/protocolize#137]
Core - GuardHexa

```
11:43:33 [SEVERE] [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
11:43:33 [SEVERE] [Protocolize] Protocolize 2.2.1:329
11:43:33 [SEVERE] [Protocolize] Stream Direction: UPSTREAM
11:43:33 [SEVERE] [Protocolize] Connection: [Usha,/79.134.198.136:58532] <-> InitialHandler
11:43:33 [SEVERE] [Protocolize] Protocol version: 340
11:43:33 [SEVERE] io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.bungee.providers.BungeeCordPacketListenerProvider.handleOutboundPacket(net.md_5.bungee.protocol.DefinedPacket, net.md_5.bungee.protocol.AbstractPacketHandler)" because "dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.LISTENER_PROVIDER" is null

11:43:33 [SEVERE]     at io.netty.handler.codec.MessageToMessageEncoder.write(:104)

11:43:33 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(:717)

11:43:33 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(:764)

11:43:33 [SEVERE]     at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(:1071)

11:43:33 [SEVERE]     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(:164)

11:43:33 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(:469)

11:43:33 [SEVERE]     at io.netty.channel.epoll.EpollEventLoop.run(:384)

11:43:33 [SEVERE]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(:986)

11:43:33 [SEVERE]     at io.netty.util.internal.ThreadExecutorMap$2.run(:74)

11:43:33 [SEVERE]     at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Exceptionflug** [comment]
Hello, please check if protocolize has been enabled successfully before joining the server.

**Comment by Ushust** [comment]
```15:29:57 [SEVERE] java.lang.RuntimeException: Unable to find supported PacketRegistrationStrategy. Maybe you are using an unsupported BungeeCord fork.

15:29:57 [SEVERE]     at dev.simplix.protocolize.bungee.providers.BungeeCordProtocolRegistrationProvider.<init>(BungeeCordProtocolRegistrationProvider.java:79)

15:29:57 [SEVERE]     at dev.simplix.protocolize.bungee.ProtocolizePlugin.onLoad(ProtocolizePlugin.java:64)

15:29:57 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(:344)

15:29:57 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(:313)

15:29:57 [SEVERE]     at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(:250)

15:29:57 [SEVERE]     at net.md_5.bungee.BungeeCord.start(:321)

15:29:57 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(:72)

15:29:57 [SEVERE]     at net.md_5.bungee.Bootstrap.main(:17)

15:29:57 [WARNING] Error loading plugin Protocolize
java.lang.NullPointerException
    at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
    at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
    at dev.simplix.protocolize.api.Protocolize.registerService(Protocolize.java:47)
    at dev.simplix.protocolize.bungee.ProtocolizePlugin.onLoad(ProtocolizePlugin.java:72)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(:344)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(:313)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(:250)
    at net.md_5.bungee.BungeeCord.start(:321)
    at net.md_5.bungee.BungeeCordLauncher.main(:72)
    at net.md_5.bungee.Bootstrap.main(:17)```

    This writes above

**Comment by Exceptionflug** [comment]
It seems like your BungeeCord version is not supported. What BungeeCord fork and version are you using?
