### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by ConnorServers** [Exceptionflug/protocolize#146]
unknown how the error was caused.

`[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:42 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:43 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:43 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:43 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:43 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:47:43 WARN] [Protocolize]: Don't know what item 322 at protocol 47 should be.
[17:48:00 WARN] [dev.simplix.protocolize.data.packets.OpenWindow]: Unknown inventory type minecraft:container in protocol version 47 for requested size 41
[17:48:00 ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[17:48:00 ERROR] [Protocolize]: Protocolize 2.2.1:356
[17:48:00 ERROR] [Protocolize]: Stream Direction: UPSTREAM
[17:48:00 ERROR] [Protocolize]: InboundConnection: [connected player] CustomEnchants (172.18.0.1/172.18.0.1:34791), ServerConnection: null
[17:48:00 ERROR] [Protocolize]: Protocol version: 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9
[17:48:00 ERROR]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.data.inventory.InventoryType.legacyTypeId(int)" because "this.inventoryType" is null
[17:48:00 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:48:00 ERROR]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:110)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
[17:48:00 ERROR]:       at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:230)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleGeneric(BackendPlaySessionHandler.java:276)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:143)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:00 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:89)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:00 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:00 ERROR]:       at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:00 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
[17:48:00 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[17:48:00 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[17:48:00 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[17:48:00 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[17:48:00 ERROR]:       at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[17:48:00 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487)
[17:48:00 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385)
[17:48:00 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
[17:48:00 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:48:00 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[17:48:00 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[17:48:00 ERROR]: Caused by: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.data.inventory.InventoryType.legacyTypeId(int)" because "this.inventoryType" is null
[17:48:00 ERROR]:       at dev.simplix.protocolize.data.packets.OpenWindow.write(OpenWindow.java:82)
[17:48:00 ERROR]:       at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.encode(VelocityProtocolizePacket.java:66)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:51)
[17:48:00 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:29)
[17:48:00 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[17:48:00 ERROR]:       ... 54 more`

**Comment by TOWUK** [comment]
1.19.1 (i have this error too, latest build from git)

**Comment by Exceptionflug** [comment]
Hello, at first please download and install the additionall legacy support module to support 1.8 clients. Then please redownload the latest protocolize velocity version from here: https://ci.exceptionflug.de/job/Protocolize2/lastStableBuild/

**Comment by KotlinFactory** [comment]
I will close this. If there is still an issue regarding this, feel free to post here and we will reopen this.
