### ISSUE TITLE
error(Connection reset by peer)

### ISSUE THREAD

**Issue by SladeGit** [Exceptionflug/protocolize#160]
**To Reproduce**
started server.. i was afk, then error and i was kicked

**Expected behavior**
[23:20:12 ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER === [23:20:12 ERROR]: [Protocolize] Protocolize 2.2.2:426 [23:20:12 ERROR]: [Protocolize] Stream Direction: UPSTREAM [23:20:12 ERROR]: [Protocolize] Connection: [/2.247.243.192:28136|SladeHD] <-> InitialHandler [23:20:12 ERROR]: [Protocolize] Protocol version: 760 [23:20:12 ERROR]: java.io.IOException: Connection reset by peer [23:20:12 ERROR]:       at java.base/sun.nio.ch.SocketDispatcher.write0(Native Method) [23:20:12 ERROR]:       at java.base/sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:54) [23:20:12 ERROR]:       at java.base/sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:137) [23:20:12 ERROR]:       at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:81) [23:20:12 ERROR]:       at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:58) [23:20:12 ERROR]:       at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:532) [23:20:12 ERROR]:       at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:415) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) [23:20:12 ERROR]:       at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:895) [23:20:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728) [23:20:12 ERROR]:       at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) [23:20:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) [23:20:12 ERROR]:       at net.md_5.bungee.netty.ChannelWrapper.close(ChannelWrapper.java:83) [23:20:12 ERROR]:       at net.md_5.bungee.UserConnection.disconnect0(UserConnection.java:433) [23:20:12 ERROR]:       at net.md_5.bungee.UserConnection.disconnect(UserConnection.java:409) [23:20:12 ERROR]:       at net.md_5.bungee.connection.UpstreamBridge.exception(UpstreamBridge.java:60) [23:20:12 ERROR]:       at net.md_5.bungee.netty.HandlerBoss.exceptionCaught(HandlerBoss.java:200) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) [23:20:12 ERROR]:       at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:92) [23:20:12 ERROR]:       at dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.exceptionCaught(ProtocolizeEncoderChannelHandler.java:45) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) [23:20:12 ERROR]:       at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143) [23:20:12 ERROR]:       at dev.simplix.protocolize.bungee.netty.ProtocolizeDecoderChannelHandler.exceptionCaught(ProtocolizeDecoderChannelHandler.java:139) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) [23:20:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [23:20:12 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [23:20:12 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) [23:20:12 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125) [23:20:12 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177) [23:20:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [23:20:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) [23:20:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) [23:20:12 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) [23:20:12 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) [23:20:12 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [23:20:12 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)

**Proxy environment**
Waterfallbungee latest

plugins: 
- AutoReconnect-1.6.11.jar
- Protocolize - ProtocolLib for BungeeCord / Waterfall / Velocity 2.2.2
- 
**Minecraft versions used**
Mc 1.19.2

**Comment by KotlinFactory** [comment]
This is not a protocolize bug.
