### ISSUE TITLE
Error when playing a sound / Wrong sound played

### ISSUE THREAD

**Issue by j-tai** [Exceptionflug/protocolize#164]
**Describe the bug**
Playing a sound to a player throws an exception:

```
java.lang.ClassCastException: class dev.simplix.protocolize.api.mapping.RangeProtocolIdMapping cannot be cast to class dev.simplix.protocolize.api.mapping.ProtocolStringMapping (dev.simplix.protocolize.api.mapping.RangeProtocolIdMapping and dev.simplix.protocolize.api.mapping.ProtocolStringMapping are in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @5e8604bf)
        at dev.simplix.protocolize.data.packets.NamedSoundEffect.<init>(NamedSoundEffect.java:74) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.playSound(ProtocolizePlayer.java:56) ~[?:?]
        at dev.simplix.protocolize.api.player.ProtocolizePlayer.playSound(ProtocolizePlayer.java:52) ~[?:?]
        at ca.jtai.protocolizetest.ProtocolizeTest.onChat(ProtocolizeTest.java:30) ~[?:?]
        at ca.jtai.protocolizetest.Lmbda$2.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.1.2-SNAPSHOT (git-1ec77eb1-b200)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**To Reproduce**
```java
ProtocolizePlayer player = Protocolize.playerProvider().player(e.getPlayer().getUniqueId());
player.playSound(Sound.ENTITY_ENDERMAN_TELEPORT, SoundCategory.MASTER, 1f, 1f);
```
Or, you can find a full Velocity plugin here: https://github.com/j-tai/ProtocolizeTest (the code runs when you type a chat message)

This code is copy-pasted from [the wiki](https://github.com/Exceptionflug/protocolize/wiki/Sounds).

**Expected behavior**
It should play a sound

**Screenshots**
n/a

**Proxy environment**
Velocity 3.1.2-SNAPSHOT (git-1ec77eb1-b200)  
Protocolize version 2.2.3:505 by Exceptionflug  
Backend: Paper 1.19.3  
Proxy plugins: protocolize

**Minecraft versions used**
Client and server are both 1.19.3

**Comment by Exceptionflug** [comment]
Hey,

this issue should be resolved with the latest build. You can download it here:
https://ci.exceptionflug.de/job/Protocolize2/

thanks for your patience.

**Comment by j-tai** [comment]
Thanks. It doesn't error anymore, but the wrong sound gets played. For example,
```java
player.playSound(Sound.BLOCK_NOTE_BLOCK_FLUTE, SoundCategory.MASTER, 1f, 1f);
```
plays an "enderman anger" sound instead of a "flute note block" sound.

**Comment by Exceptionflug** [comment]
This should hopefully be fixed in 2.2.4

**Comment by j-tai** [comment]
2.2.4 is still playing the wrong sounds for me.

**Comment by Exceptionflug** [comment]
Will be tracked in https://github.com/Exceptionflug/protocolize/issues/171
