### ISSUE TITLE
error when playing anything sound for 1.8

### ISSUE THREAD

**Issue by AkariDream** [Exceptionflug/protocolize#166]
**Describe the bug**
as soon as 1.8 the client hears the sound. an error occurs. the 1.8 client did not receive sound.

**To Reproduce**
loading protocolize and legacy support onto waterfall
join the server using 1.8
play a sound. for example have another player walk around a player using a 1.8 client.

**Expected behavior**
sound can be heard. no error occurs

**Screenshots**
[errlog](https://pastebin.com/a4AbQkPe)

**Proxy environment**
Waterfall-1.19-507

BungeeHub 4.4
JPremium-Cleared-1.16.1
JoinCommands(Sirblobman) 2.0.9
LiteBans (forget version)
LuckPerms (Bungee 5.4.52)
Maintenance (4.0.1)
SQLiteDriver (forget version)
SkinsRestorer (forget version. should be latest)
TAB (3.1.5)
UltimateFriends (forget version. should be latest)
ajQueuePlus (2.2.9)
CleanStaffChat (1.7)
HAProxy Detector (3.0.2)
MiniMotd (2.0.9)
nAntiBot (6.0.7)
Plugin Hide Pro (2.6.5)
Protocolize and legacy support. latest version should be now.

**Minecraft versions used**
Backend server: Akarin 1.16.5 6be3d57(latest build)
Client: vanilla 1.8.9

**Comment by LaserSlime** [comment]
Same error for me with a 1.18.2 client.

**Comment by AkariDream** [comment]
what is certain, though. It works on 1.19.

**Comment by AkariDream** [comment]
new err:
using fishing_rod on 1.19 client:
`[13:59:44 ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[13:59:44 ERROR]: [Protocolize] Protocolize 2.2.3:506
[13:59:44 ERROR]: [Protocolize] Stream Direction: DOWNSTREAM
[13:59:44 ERROR]: [Protocolize] Connection: Akkariin_
[13:59:44 ERROR]: [Protocolize] Protocol version: 760
[13:59:44 ERROR]: io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.NamedSoundEffect at protocol version 760 in direction TO_CLIENT
[13:59:44 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:59:44 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:59:44 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[13:59:44 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:59:44 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[13:59:44 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[13:59:44 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[13:59:44 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:59:44 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[13:59:44 ERROR]: Caused by: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.NamedSoundEffect at protocol version 760 in direction TO_CLIENT
[13:59:44 ERROR]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(57) + length(8) exceeds writerIndex(58): PooledSlicedByteBuf(ridx: 57, widx: 58, cap: 58/58, unwrapped: PooledUnsafeDirectByteBuf(ridx: 59, widx: 59, cap: 192))
[13:59:44 ERROR]:       at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[13:59:44 ERROR]:       at io.netty.buffer.AbstractByteBuf.readLong(AbstractByteBuf.java:835)
[13:59:44 ERROR]:       at dev.simplix.protocolize.data.packets.NamedSoundEffect.read(NamedSoundEffect.java:105)
[13:59:44 ERROR]:       at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:48)
[13:59:44 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[13:59:44 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[13:59:44 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:59:44 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:59:44 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[13:59:44 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[13:59:44 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[13:59:44 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[13:59:44 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[13:59:44 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[13:59:44 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[13:59:44 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[13:59:44 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[13:59:44 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by Exceptionflug** [comment]
Hey,

this issue should be resolved with the latest build. You can download it here:
https://ci.exceptionflug.de/job/Protocolize2/

thanks for your patience.

**Comment by AkariDream** [comment]
> Hey,
> 
> this issue should be resolved with the latest build. You can download it here: https://ci.exceptionflug.de/job/Protocolize2/
> 
> thanks for your patience.

![image](https://user-images.githubusercontent.com/71176602/208404884-aa5b731d-bc86-4703-84ea-e87633af9990.png)
bruh

**Comment by Exceptionflug** [comment]
Yeah a few minutes after release my server died ._.

Just use one of the binaries I sent in the #protocolize discord channel: https://discord.simplix.dev/ or wait until my server is back up again.

**Comment by AkariDream** [comment]
it should work fine now. if I run into the problem again. i think i'll reopen this issue.
