### ISSUE TITLE
Can't join 1.19.3 server

### ISSUE THREAD

**Issue by x1p** [Exceptionflug/protocolize#167]
**Describe the bug**
I can't join a bungee network.
Client gets a message, see screenshots

This error appears once on the bungee console.
<details>
  <summary>Error, click to open</summary>
  
 ```
[20:54:28] [Netty Worker IO Thread #1/ERROR] [dev.simplix.protocolize.api.util.DebugUtil]: Unable to write dump file Wed-Dec-14-20:54:28-CET-2022.zip
java.io.IOException: Stream closed
at java.util.zip.ZipOutputStream.ensureOpen(ZipOutputStream.java:96) ~[?:?]
at java.util.zip.ZipOutputStream.closeEntry(ZipOutputStream.java:257) ~[?:?]
at dev.simplix.protocolize.api.util.DebugUtil.writeDump(DebugUtil.java:45) ~[?:?]
at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:57) ~[?:?]
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:13085b9:510]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:54:28] [Netty Worker IO Thread #1/ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[20:54:28] [Netty Worker IO Thread #1/ERROR]: [Protocolize] Protocolize 2.2.3:507
[20:54:28] [Netty Worker IO Thread #1/ERROR]: [Protocolize] Stream Direction: DOWNSTREAM
[20:54:28] [Netty Worker IO Thread #1/ERROR]: [Protocolize] Connection: Mammut10
[20:54:28] [Netty Worker IO Thread #1/ERROR]: [Protocolize] Protocol version: 761
[20:54:28] [Netty Worker IO Thread #1/ERROR]: io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.NamedSoundEffect at protocol version 761 in direction TO_CLIENT
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at java.base/java.lang.Thread.run(Thread.java:833)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: Caused by: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.NamedSoundEffect at protocol version 761 in direction TO_CLIENT
[20:54:28] [Netty Worker IO Thread #1/ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 109 out of bounds for length 10
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at dev.simplix.protocolize.data.packets.NamedSoundEffect.read(NamedSoundEffect.java:93)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:48)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:54:28] [Netty Worker IO Thread #1/ERROR]: at java.base/java.lang.Thread.run(Thread.java:833)
 ```
 
 </details>
Returning to protocollize-bungee build 504, everything works normally.
Note: When running a 1.19.2 (or lower) version server behind the bungee lets you join that 1.19.2 server. Until you try to switch to a 1.19.3 server in that bungee network.

**To Reproduce**
1. Setup Waterfall with protocollize build 506/507
2. Setup a Test server running paper like 1.19.3
3. Try joining.

**Expected behavior**
Join a bungee network without getting kicked

**Screenshots**
![Screenshot 2022-12-14 205659](https://user-images.githubusercontent.com/28690790/207701488-3bad9dec-f16c-4fe6-bf6f-4dbf182c1ce5.png)

**Proxy environment**
Waterfall build 510

**Minecraft versions used**
Server:
  Waterfall build 510 + protocollize 507 + viaversion build 664 + viabackwards build 294
  Paper like server connected to that bungee running 1.19.3
Client:
  1.19.2 or 1.19.3

**Comment by Exceptionflug** [comment]
Hey,

this issue should be resolved with the latest build. You can download it here:
https://ci.exceptionflug.de/job/Protocolize2/

thanks for your patience.

**Comment by x1p** [comment]
Thank you. I will test as soon as your site works again. It's currently down for a while.

**Comment by x1p** [comment]
Tried with build 515: no luck
```
disconnected with: DecoderException : net.md_5.bungee.protocol.BadPacketException: Couldn't read all bytes from a packet. For more information, launch Waterfall with -Dwaterfall.packet-decode-logging=true @ io.netty.handler.codec.MessageToMessageDecoder:98
```

**Comment by Ceddix** [comment]
Yeah, I actually still get exactly the same error

**Comment by x1p** [comment]
build 518 seems to work
