### ISSUE TITLE
1.19.2 Switching servers

### ISSUE THREAD

**Issue by x1p** [Exceptionflug/protocolize#173]
**Describe the bug**
A player switching from one 1.19.2 server to another 1.19.2 server gets kicked with this error on the console:
`bad packet, are mods in use!? Protocolize is unable to read packet dev.simplix.protocolize.data.packets.SoundEffect at protocol version 760 in direction TO_CLIENT`

Earlier today multiple extensive errors occured as well with this same player. Probably the same issue.
<details>
  <summary>Error, click to open</summary>
  
 ```
[11:27:19] [Netty Worker IO Thread #6/ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[11:27:19] [Netty Worker IO Thread #6/ERROR]: [Protocolize] Protocolize 2.2.4:519
[11:27:19] [Netty Worker IO Thread #6/ERROR]: [Protocolize] Stream Direction: DOWNSTREAM
[11:27:19] [Netty Worker IO Thread #6/ERROR]: [Protocolize] Connection: Player123abc
[11:27:19] [Netty Worker IO Thread #6/ERROR]: [Protocolize] Protocol version: 760
[11:27:19] [Netty Worker IO Thread #6/ERROR]: io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.SoundEffect at protocol version 760 in direction TO_CLIENT
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: Caused by: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.SoundEffect at protocol version 760 in direction TO_CLIENT
[11:27:19] [Netty Worker IO Thread #6/ERROR]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 8020 out of bounds for length 10
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at dev.simplix.protocolize.data.packets.SoundEffect.read(SoundEffect.java:106)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:48)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[11:27:19] [Netty Worker IO Thread #6/ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)

 ```
 
 </details>

**To Reproduce**
I'm not able to reproduce this easily

**Expected behavior**

**Screenshots**
n/a

**Proxy environment**
Waterfall build 510
Protocolize build 519

**Minecraft versions used**
1.19.2

**Comment by Exceptionflug** [comment]
Hey,

there sould be a folder called `protocolize-logs` inside your proxy server folder. It should containt a zip file containing the packet which was not completely read. Can you share me that zip file?

**Comment by x1p** [comment]
Sure. I have 161 files from that day. I'll give you the first and last.
[21-12-2022-11-27-19.zip](https://github.com/Exceptionflug/protocolize/files/10290495/21-12-2022-11-27-19.zip)
[21-12-2022-23-25-53.zip](https://github.com/Exceptionflug/protocolize/files/10290497/21-12-2022-23-25-53.zip)

**Comment by Exceptionflug** [comment]
Can you try the latest build?
https://ci.exceptionflug.de/job/Protocolize2/

**Comment by x1p** [comment]
I can try, but as I cannot reproduce myself on a test server, I only have real players to test with. So if it happens again, players happiness is affected.

**Comment by Exceptionflug** [comment]
Players happiness is not affected that much because it only happens for some hard coded game sound events which just get not played for the player.

**Comment by x1p** [comment]
When made this issue specifically for a player who got kicked and could not join the server. When I reverted to build 504 she could play again. I'm not worried about sounds not working. I'm being cautious when players possibly can't play.
It's on the server working after the restart. So hopefully we have some results tomorrow.

**Comment by x1p** [comment]
All was going well these past days. (Otherwise you would have heard me sooner).
Until I saw this today from a player that got kicked because of connection issues (already connected to proxy).

<details>
  <summary>Console error, click to open</summary>
  
 ```
[Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[Protocolize] Protocolize 2.2.4:522
[Player123ABC] disconnected with: You are already connected to this proxy!
[/123.123.123.123:53481|Player123ABC] <-> DownstreamBridge <-> [Lobby] has disconnected
[/123.123.123.123:53481|Player123ABC] -> UpstreamBridge has disconnected
[Protocolize] Stream Direction: UPSTREAM
[Protocolize] Connection: [/123.123.123.123:53487|Player123ABC] <-> InitialHandler
[Protocolize] Protocol version: 760
io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:311)
	at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:60)
	at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:153)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:767)
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:618)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
	at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at java.base/jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.base/java.lang.reflect.Field.get(Field.java:425)
	at dev.simplix.protocolize.bungee.util.ReflectionUtil.getProtocolVersion(ReflectionUtil.java:164)
	at dev.simplix.protocolize.bungee.player.BungeeCordProtocolizePlayer.protocolVersion(BungeeCordProtocolizePlayer.java:91)
	at dev.simplix.protocolize.bungee.ProtocolizePlugin.lambda$onEnable$0(ProtocolizePlugin.java:102)
	at dev.simplix.protocolize.bungee.providers.BungeeCordProtocolizePlayerProvider.lambda$player$0(BungeeCordProtocolizePlayerProvider.java:33)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at dev.simplix.protocolize.bungee.providers.BungeeCordProtocolizePlayerProvider.lambda$player$1(BungeeCordProtocolizePlayerProvider.java:33)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at dev.simplix.protocolize.bungee.providers.BungeeCordProtocolizePlayerProvider.player(BungeeCordProtocolizePlayerProvider.java:31)
	at dev.simplix.protocolize.bungee.providers.BungeeCordPacketListenerProvider.createSendEvent(BungeeCordPacketListenerProvider.java:209)
	at dev.simplix.protocolize.bungee.providers.BungeeCordPacketListenerProvider.handleOutboundPacket(BungeeCordPacketListenerProvider.java:93)
	at dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.encode(ProtocolizeEncoderChannelHandler.java:30)
	at dev.simplix.protocolize.bungee.netty.ProtocolizeEncoderChannelHandler.encode(ProtocolizeEncoderChannelHandler.java:19)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	... 17 more
 ```
 
 </details>
 So maybe related, maybe not. If not: I can make a separate issue if desired.
 Looking back at the logs, I had exactly the same once under the same conditions with another player.
 Besides this, it's working quite good now.

**Comment by x1p** [comment]
I guess I'll close my ticket and hope you have read it since it fixed
