### ISSUE TITLE
Velocity Inventory Bug

### ISSUE THREAD

**Issue by smuddgge** [Exceptionflug/protocolize#174]
**Describe the bug**
When trying to open a inventory, a error occurs.

```
[21:27:15 ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[21:27:15 ERROR] [Protocolize]: Protocolize 2.2.3:505
[21:27:15 ERROR] [Protocolize]: Stream Direction: UPSTREAM
[21:27:15 ERROR] [Protocolize]: InboundConnection: [connected player] Smudyy (/81.140.211.156:57164), ServerConnection: null
[21:27:15 ERROR] [Protocolize]: Protocol version: 1.19.1, 1.19.2
[21:27:15 ERROR]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "str" is null
[21:27:15 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[21:27:15 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:27:15 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[21:27:15 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[21:27:15 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[21:27:15 ERROR]:       at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[21:27:15 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[21:27:15 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940)
[21:27:15 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
[21:27:15 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
[21:27:15 ERROR]:       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
[21:27:15 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
[21:27:15 ERROR]:       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
[21:27:15 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[21:27:15 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[21:27:15 ERROR]:       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[21:27:15 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[21:27:15 ERROR]: Caused by: java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "str" is null
[21:27:15 ERROR]:       at dev.simplix.protocolize.api.util.ProtocolUtil.writeString(ProtocolUtil.java:161)
[21:27:15 ERROR]:       at dev.simplix.protocolize.data.packets.OpenWindow.write(OpenWindow.java:90)
[21:27:15 ERROR]:       at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.encode(VelocityProtocolizePacket.java:66)
[21:27:15 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:51)
[21:27:15 ERROR]:       at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:29)
[21:27:15 ERROR]:       at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[21:27:15 ERROR]:       ... 16 more
```

**Inventory Code**
```java
this.inventory = new Inventory(InventoryType.GENERIC_9X6);
this.inventory.item(0, new ItemStack(ItemType.LIGHT_GRAY_STAINED_GLASS_PANE));
ProtocolizePlayer player = Protocolize.playerProvider().player(user.getUniqueId());
player.openInventory(this.inventory);
```

**Expected behavior**
The inventory to open with 1 light grey stained glass.

**Proxy environment**
`Velocity 3.1.2-SNAPSHOT (git-2d072151-b185)`

**Minecraft versions used**
1.19.2

**Comment by Exceptionflug** [comment]
Hey, you are using an outdated version of protocolize and you need to specify an inventory title before sending the inventory
