### ISSUE TITLE
Error on Velocity 3.2.0-SNAPSHOT

### ISSUE THREAD

**Issue by CoachYT1** [Exceptionflug/protocolize#175]
**Describe the bug**
Protocolize throws an error when swapping channel initializer.
`[12:16:17 INFO] [protocolize]: ======= PROTOCOLIZE =======
[12:16:17 INFO] [protocolize]: Version 2.2.4:537 by Exceptionflug
[12:16:17 INFO] [protocolize]: Swap channel initializers (ignore the following two warnings)...
[12:16:17 INFO] [dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer]: Respecting the previous registered BackendChannelInitializer: com.velocitypowered.proxy.network.BackendChannelInitializer
[12:16:17 WARN]: The backend channel initializer has been replaced by dev.simplix.protocolize.velocity.ProtocolizePlugin.swapChannelInitializers(ProtocolizePlugin.java:133)
[12:16:17 INFO] [dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer]: Respecting the previous registered ServerChannelInitializer: com.velocitypowered.proxy.network.ServerChannelInitializer
[12:16:17 WARN]: The server channel initializer has been replaced by dev.simplix.protocolize.velocity.ProtocolizePlugin.swapChannelInitializers(ProtocolizePlugin.java:135)
[12:16:17 INFO] [protocolize]: Swapped channel initializers
[12:16:17 ERROR]: Couldn't pass ProxyInitializeEvent to protocolize
java.lang.IllegalAccessError: class dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider tried to access protected field com.velocitypowered.proxy.protocol.StateRegistry.clientbound (dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @1abc9f14; com.velocitypowered.proxy.protocol.StateRegistry is in unnamed module of loader 'app')
        at dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider.registerPacket(VelocityProtocolRegistrationProvider.java:80) ~[?:?]
        at dev.simplix.protocolize.data.DataModule.registerPackets(DataModule.java:109) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityModuleProvider.enableModule(VelocityModuleProvider.java:74) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityModuleProvider.enableAll(VelocityModuleProvider.java:68) ~[?:?]
        at dev.simplix.protocolize.velocity.ProtocolizePlugin.onInit(ProtocolizePlugin.java:112) ~[?:?]
        at dev.simplix.protocolize.velocity.Lmbda$8.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.2.0-SNAPSHOT-216.jar:3.2.0-SNAPSHOT (git-697d08ba-b216)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[12:16:17 INFO] [ProtocolizeLegacySupport]: Legacy support enabled.
[12:16:17 INFO] [Protocolize]: Enabled module dev.simplix.protocolize.legacy.LegacyModule`

**To Reproduce**
Install Velocity build 216 and protocolize latest build

**Expected behavior**
Server should start without errors

**Screenshots**
https://prnt.sc/kF9VNZi2cYVe

**Proxy environment**
Velocity #216

**Comment by HyCore** [comment]
same

**Comment by CoachYT1** [comment]
> The latest build should fix this: [ci.exceptionflug.de/job/Protocolize2](https://ci.exceptionflug.de/job/Protocolize2/)

Yes, it does
