### ISSUE TITLE
Sounds crash clients

### ISSUE THREAD

**Issue by smuddgge** [Exceptionflug/protocolize#178]
**Velocity** 3.2.0
**Protocolize** 2.2.5:577

```java
ProtocolizePlayer player = Protocolize.playerProvider().player(playerUuid);
player.playSound(Sound.BLOCK_BELL_RESONATE, SoundCategory.MASTER, 1f, 1f);
```

<img width="1771" alt="Screenshot 2023-02-05 at 00 20 21" src="https://user-images.githubusercontent.com/68658429/216795196-c0976054-8e05-45df-aec6-9366f803fb88.png">

**Comment by Exceptionflug** [comment]
Which client version?

**Comment by smuddgge** [comment]
1.19.3

**Comment by smuddgge** [comment]
```
[17:21:41 INFO] [protocolize]: ======= PROTOCOLIZE =======
[17:21:41 INFO] [protocolize]: Version 2.2.4:519 by Exceptionflug
[17:21:41 INFO] [protocolize]: Swap channel initializers (ignore the following two warnings)...
[17:21:41 INFO] [dev.simplix.protocolize.velocity.netty.ProtocolizeBackendChannelInitializer]: Respecting the previous registered BackendChannelInitializer: com.velocitypowered.proxy.network.BackendChannelInitializer
[17:21:41 WARN]: The backend channel initializer has been replaced by dev.simplix.protocolize.velocity.ProtocolizePlugin.swapChannelInitializers(ProtocolizePlugin.java:133)
[17:21:41 INFO] [dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer]: Respecting the previous registered ServerChannelInitializer: com.velocitypowered.proxy.network.ServerChannelInitializer
[17:21:41 WARN]: The server channel initializer has been replaced by dev.simplix.protocolize.velocity.ProtocolizePlugin.swapChannelInitializers(ProtocolizePlugin.java:135)
[17:21:41 INFO] [protocolize]: Swapped channel initializers
[17:21:42 ERROR]: Couldn't pass ProxyInitializeEvent to protocolize
java.lang.IllegalAccessError: class dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider tried to access protected field com.velocitypowered.proxy.protocol.StateRegistry.clientbound (dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider is in unnamed module of loader com.velocitypowered.proxy.plugin.PluginClassLoader @7a7d1b47; com.velocitypowered.proxy.protocol.StateRegistry is in unnamed module of loader 'app')
        at dev.simplix.protocolize.velocity.providers.VelocityProtocolRegistrationProvider.registerPacket(VelocityProtocolRegistrationProvider.java:80) ~[?:?]
        at dev.simplix.protocolize.data.DataModule.registerPackets(DataModule.java:113) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityModuleProvider.enableModule(VelocityModuleProvider.java:74) ~[?:?]
        at dev.simplix.protocolize.velocity.providers.VelocityModuleProvider.enableAll(VelocityModuleProvider.java:68) ~[?:?]
        at dev.simplix.protocolize.velocity.ProtocolizePlugin.onInit(ProtocolizePlugin.java:112) ~[?:?]
        at dev.simplix.protocolize.velocity.Lmbda$6.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-225.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-225.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-225.jar:3.2.0-SNAPSHOT (git-8761d02d-b225)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:21:42 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25583
```

Error on start up

**Comment by smuddgge** [comment]
@Exceptionflug 

Velocity `3.2.0`
Protocolize `2.2.4:519`
Minecraft `1.19.3`
