### ISSUE TITLE
Can't send SoundEffect packet to 1.19.4 client

### ISSUE THREAD

**Issue by j-tai** [Exceptionflug/protocolize#185]
**Describe the bug**
Sending a SoundEffect packet to a 1.19.4 client throws an exception.
```
[22:00:04 ERROR]: Couldn't pass PlayerChatEvent to protocolizetest
java.lang.IllegalStateException: Cannot send dev.simplix.protocolize.data.packets.SoundEffect to players with protocol version 762
        at dev.simplix.protocolize.velocity.player.VelocityProtocolizePlayer.sendPacket(VelocityProtocolizePlayer.java:54) ~[?:?]
        at ca.jtai.protocolizetest.ProtocolizeTest.onChat(ProtocolizeTest.java:31) ~[?:?]
        at ca.jtai.protocolizetest.Lmbda$2.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-01f1e1a9-b243)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**To Reproduce**
```java
ProtocolizePlayer player = Protocolize.playerProvider().player(e.getPlayer().getUniqueId());
var loc = player.location();
player.sendPacket(new SoundEffect(
    887, SoundCategory.MASTER, loc.x(), loc.y(), loc.z(), 1f, 1f
));
```

**Expected behavior**
It should play a sound

**Screenshots**
N/A

**Proxy environment**
Velocity 3.2.0-SNAPSHOT (git-01f1e1a9-b243)
No plugins other than Protocolize and a test plugin containing the code above

**Minecraft versions used**
Client: 1.19.4, server: Paper 1.19.4

**Comment by Exceptionflug** [comment]
Hey,
the issue should be resolved now by downloading the latest version of protocolize from our CI: https://ci.exceptionflug.de/job/Protocolize2/lastSuccessfulBuild/artifact/protocolize-velocity/target/protocolize-velocity.jar

**Comment by j-tai** [comment]
Thanks, it's fixed on the latest build.
