### ISSUE TITLE
Error when opening a stonecutter

### ISSUE THREAD

**Issue by j-tai** [Exceptionflug/protocolize#187]
**Describe the bug**

Right-clicking on a stonecutter logs the following error and fails to open the stonecutter GUI.
```
[19:09:10] [Netty epoll Worker #0/WARN] [dev.simplix.protocolize.data.packets.OpenWindow]: Unknown inventory type 24 in protocol version 762
[19:09:10] [Netty epoll Worker #0/ERROR] [Protocolize]: === EXCEPTION CAUGHT IN DECODER ===
[19:09:10] [Netty epoll Worker #0/ERROR] [Protocolize]: Protocolize 2.2.6:626
[19:09:10] [Netty epoll Worker #0/ERROR] [Protocolize]: Stream Direction: UPSTREAM
[19:09:10] [Netty epoll Worker #0/ERROR] [Protocolize]: InboundConnection: [connected player] <redacted> (/127.0.0.1:39328), ServerConnection: null
[19:09:10] [Netty epoll Worker #0/ERROR] [Protocolize]: Protocol version: 1.19.4
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.data.inventory.InventoryType.getTypeId(int)" because "this.inventoryType" is null
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.connection.MinecraftConnection.delayedWrite(MinecraftConnection.java:233)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler.handleGeneric(BackendPlaySessionHandler.java:311)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.connection.MinecraftConnection.channelRead(MinecraftConnection.java:144)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.protocol.netty.AutoReadHolderHandler.channelRead(AutoReadHolderHandler.java:57)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:92)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:61)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: Caused by: java.lang.NullPointerException: Cannot invoke "dev.simplix.protocolize.data.inventory.InventoryType.getTypeId(int)" because "this.inventoryType" is null
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at dev.simplix.protocolize.data.packets.OpenWindow.write(OpenWindow.java:90)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at dev.simplix.protocolize.velocity.packet.VelocityProtocolizePacket.encode(VelocityProtocolizePacket.java:66)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:54)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at com.velocitypowered.proxy.protocol.netty.MinecraftEncoder.encode(MinecraftEncoder.java:32)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
[19:09:10] [Netty epoll Worker #0/ERROR] [com.velocitypowered.proxy.console.VelocityConsole]: 	... 54 more
```

**To Reproduce**
1. Place a stonecutter
2. Right-click on it

**Expected behavior**
The stonecutter GUI should open, and no error should be logged.

**Screenshots**
N/A

**Proxy environment**
Velocity 3.2.0-SNAPSHOT (git-01f1e1a9-b243)
Protocolize version 2.2.6:626 by Exceptionflug
No plugins other than Protocolize

**Minecraft versions used**
1.19.4 client, Paper 1.19.4 server

**Comment by HolographicWings** [comment]
`new InventoryProtocolIdMapping(477, 762, 23, 2)`
to
`new InventoryProtocolIdMapping(477, 761, 23, 2), new InventoryProtocolIdMapping(762, 762, 24, 2)`
in dev.simplix.protocolize.data.inventory.InventoryType line 43 by decompiling and recompiling the .class fixed the issue for me

**Comment by itsTyrion** [comment]
could you make that a pull request so it can be merged? @HolographicWings

**Comment by iVillager** [comment]
Bump! This is happening to me too

**Comment by james090500** [comment]
This is fairly game breaking can we prioritise.

**Comment by KotlinFactory** [comment]
@Exceptionflug

**Comment by HolographicWings** [comment]
> 

impossible, the dev.simplix.protocolize.data package is not in the repo, so we can't even build the plugin, it is uncomplete

**Comment by Athar42** [comment]
@Exceptionflug Sorry to reopen, but as the plugin is not rebuild, this is still NOT fixed.
Having this issue too with release 2.2.6 (dated from march, your update is from April).

Should look to add the other bugfix for this issue I guess : https://github.com/Exceptionflug/protocolize/issues/190
