### ISSUE TITLE
Velocity does not work

### ISSUE THREAD

**Issue by smuddgge** [Exceptionflug/protocolize#188]
Just downloaded protocolize fresh from spigot and won't work.
Version `2.2.4`
Minecraft `1.19.3`
Velocity `3.2.0-SNAPSHOT (git-9149ed33-b230)`

```
[14:32:57 ERROR]: Unable to load plugin plugins/protocolize-velocity.jar
com.velocitypowered.api.plugin.InvalidPluginException: Did not find a valid velocity-plugin.json.
        at com.velocitypowered.proxy.plugin.loader.java.JavaPluginLoader.loadCandidate(JavaPluginLoader.java:67) ~[velocity-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
        at com.velocitypowered.proxy.plugin.VelocityPluginManager.loadPlugins(VelocityPluginManager.java:96) ~[velocity-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
        at com.velocitypowered.proxy.VelocityServer.loadPlugins(VelocityServer.java:345) ~[velocity-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
        at com.velocitypowered.proxy.VelocityServer.start(VelocityServer.java:227) ~[velocity-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
        at com.velocitypowered.proxy.Velocity.main(Velocity.java:69) ~[velocity-230.jar:3.2.0-SNAPSHOT (git-9149ed33-b230)]
```

**Comment by smuddgge** [comment]
Spigot link : https://www.spigotmc.org/resources/protocolize-protocollib-for-bungeecord-waterfall-velocity.63778/

**Comment by smuddgge** [comment]
Fixed it! For some reason it wasn't downloading onto the server correctly, but I managed to do it now :3

**Comment by KotlinFactory** [comment]
Good to hear & thanks for closing this!
