### ISSUE TITLE
Error on the 1.20.2

### ISSUE THREAD

**Issue by liquidman228** [Exceptionflug/protocolize#198]
**Describe the bug**
Error preventing to log in to the server from version 1.20.2
NOTE: On vanilla bungeecord 1.20.2 the error still exists, but i can join the server

**To Reproduce**
1. Start a flamecord server with protocolize
2. Try to join on 1.20.2
3. Get the error

**Expected behavior**
A normal join

**Screenshots**
I think a full console error will be more useful
`[00:12:07 ERROR]: [Protocolize] Problem while getting connection from [/127.0.0.1:56477|L1quid_man] <-> DownstreamBridge <-> [auth] (net.md_5.bungee.connection.DownstreamBridge)
[00:12:07 WARN]: Error dispatching event ServerConnectedEvent(player=L1quid_man, server=net.md_5.bungee.ServerConnection@4180479e) to listener dev.simplix.protocolize.bungee.listener.PlayerListener@3d8b9dee
java.lang.RuntimeException: Unable to obtain connection
        at dev.simplix.protocolize.bungee.util.ReflectionUtil.getConnection(ReflectionUtil.java:91) ~[?:?]
        at dev.simplix.protocolize.bungee.netty.ProtocolizeDecoderChannelHandler.<init>(ProtocolizeDecoderChannelHandler.java:41) ~[?:?]
        at dev.simplix.protocolize.bungee.listener.PlayerListener.onServerSwitch(PlayerListener.java:52) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:511) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:238) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:817) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:283) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:140) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:58e0aa3:unknown]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set final net.md_5.bungee.UserConnection field net.md_5.bungee.connection.UpstreamBridge.con to net.md_5.bungee.connection.DownstreamBridge
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
        at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
        at dev.simplix.protocolize.bungee.util.ReflectionUtil.getConnection(ReflectionUtil.java:88) ~[?:?]
        ... 43 more`

**Proxy environment**
FlameCord 1.20.2

Plugins:
- AuthmeBungee
- Bungeeguard
- Fallbackserver
- floodgate-bungee
- Geyser-bungeecord
- Libertybans
- minimotd
- Neoprotect
- Pl-hide-pro
- protocolize-bungeecord
- Skinsrestorer
- Spark

**Minecraft versions used**
Java 1.20.2 

Should i contact a Flamecord developer about this issue?

**Comment by liquidman228** [comment]
Hi, sorry, i forgot to tell that it was fixed with the latest version of the plugin, lol
Anyways thank you for your answer and the plugin
