### ISSUE TITLE
Velocity build 276/290 error console

### ISSUE THREAD

**Issue by BartosB13** [Exceptionflug/protocolize#204]
Velocity latest build 276
I don't know what causes this error

```
[20:58:49 ERROR] [dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer]: There was a problem while calling the underlying server channel initializer
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-81b183ac-b276)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
        at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70) ~[?:?]
        ... 24 more
```

**Comment by buffolollo** [comment]
getting same error

**Comment by Exceptionflug** [comment]
Should be fixed in the latest release:
https://ci.exceptionflug.de/job/Protocolize2/lastSuccessfulBuild/artifact/protocolize-velocity/target/protocolize-velocity.jar

**Comment by BartosB13** [comment]
Today I updated the plugin, when joining the server and refreshing the server list I still get an error on the console.
After the first test, I also increased the Velocity build to the current one, i.e. 290. The error still occurs.
Could some other plugins be the problem? Is this a problem directly with Protocolize?

```
[14:01:49 ERROR] [dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer]: There was a problem while calling the underlying server channel initializer
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at dev.simplix.protocolize.velocity.netty.ProtocolizeServerChannelInitializer.initChannel(ProtocolizeServerChannelInitializer.java:46) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:3.2.0-SNAPSHOT (git-67d5e77b-b290)]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'com.velocitypowered.proxy.connection.MinecraftSessionHandler com.velocitypowered.proxy.connection.MinecraftConnection.getSessionHandler()'
        at net.elytrium.fastmotd.injection.ServerChannelInitializerHook.initChannel(ServerChannelInitializerHook.java:70) ~[?:?]
        ... 24 more
```

**Comment by Exceptionflug** [comment]
Does this issue still occur on the latest Velocity and Protocolize versions?
