### ISSUE TITLE
FlameCord Support

### ISSUE THREAD

**Issue by linsaftw** [Exceptionflug/protocolize#226]
Please add support for FlameCord. Leave bytebuf untouched. Reset the indexes for writer and reader. Thanks!

**Comment by Exceptionflug** [comment]
I'm not a big fan of maintaining support for closed-source projects myself. But you can feel free to create a pull request for this since I guess you know best on what to change to make it compatible.

**Comment by nhanledev** [comment]
I got this when open a menu on flamecord 1.9.3

```
[23:27:44 WARN]: [/10.0.0.80:53622|HibaraMamoru] -> UpstreamBridge - could not decode packet!
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1
        at io.netty.util.internal.ReferenceCountUpdater.toLiveRealRefCnt(ReferenceCountUpdater.java:83) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:148) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:90) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90) ~[flamecord-1.9.3.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:8a3326a:unknown]
        ... 22 more
[23:27:44 INFO]: [HibaraMamoru] disconnected with: DecoderException : io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1 @ io.netty.handler.codec.MessageToMessageDecoder:98
```

**Comment by linsaftw** [comment]
The problem is you are manipulating the bytebuf and not resetting the indexes, bungeecord resets it by doing a very heavy operation (.copy()) flamecord removes this heavy operation to save resources but plugins that do not take in count index has to be reset fall into this problem.

**Comment by MachineBreaker** [comment]
> The problem is you are manipulating the bytebuf and not resetting the indexes, bungeecord resets it by doing a very heavy operation (.copy()) flamecord removes this heavy operation to save resources but plugins that do not take in count index has to be reset fall into this problem.

Feel free to open a pull request to fix the issues introduced by your proxy

**Comment by linsaftw** [comment]
> > The problem is you are manipulating the bytebuf and not resetting the indexes, bungeecord resets it by doing a very heavy operation (.copy()) flamecord removes this heavy operation to save resources but plugins that do not take in count index has to be reset fall into this problem.
> 
> Feel free to open a pull request to fix the issues introduced by your proxy

This is an issue introduced by lack of knowledge on the netty pipeline. You cannot change a packet data and then leave the index changed. About the PR I will of course make it as soon as I have available time.

**Comment by Exceptionflug** [comment]
Which JDK version are you using for compilation? I'm using OpenJDK 19.

**Comment by linsaftw** [comment]
> Which JDK version are you using for compilation? I'm using OpenJDK 19.

21 and tried 8 too

**Comment by linsaftw** [comment]
> I'm using the bundled IntelliJ maven installation and OpenJDK 19 as already said. I did not experience something like this before.

Just add a resetReaderIndex for each time you finish reading bytes on a packet. You probably have to change just one line.

**Comment by Exceptionflug** [comment]
A fix is now included in the nightly build for tomorrow.

**Comment by linsaftw** [comment]
> A fix is now included in the nightly build for tomorrow.

Thank you!!!!
