### ISSUE TITLE
Unable to read packet ClickWindow

### ISSUE THREAD

**Issue by HielkeMaps** [Exceptionflug/protocolize#227]
**Describe the bug**
On my server I have menus that work with inventories. For example a shop GUI, and a cosmetics menu. When clicking on an item in the inventory menu, Protocollize throws an error, and the menu action doesn't work.
Because this happens with both the UltraCosmetics Menu and UltimateGUI plugins, as well, I feel like this is a Protocollize bug.

**To Reproduce**
1. Using UltraCosmetics, open the cosmetics menu.
2. Click on any item in the inventory.
3. Watch Protocollize throw an error.

**Expected behavior**
No errors shown, clicking a menu item works as intended.

**Proxy environment**
Running BungeeCord network with 1.20.4 Paper server.
I have ViaVersion installed on the Paper server. Also using Ultra Cosmetics for the cosmetics menu.

**Minecraft versions used**
Minecraft 1.20.4

**Error**
```
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at java.lang.Thread.run(Thread.java:748)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
24.01 03:56:31 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
24.01 03:56:31 [Multicraft] Skipped 39 lines due to rate limit (30/s)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.ClickWindow at protocol version 765 in direction TO_SERVER
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR [Protocolize] Protocol version: 765
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR [Protocolize] Connection: [/1.64.253.25:50170|Hielke] <-> InitialHandler
24.01 03:56:29 [Server] Netty Worker IO Thread #0/ERROR [Protocolize] Stream Direction: UPSTREAM
```

**Comment by Exceptionflug** [comment]
Hey, the log you sent seems uncomplete. Can you sending a full log of this error?

**Comment by HielkeMaps** [comment]
Hey!

Just realized the error is also thrown when attempting to trade with a villager. Here's the error:

```[15:14:47 ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[15:14:47 ERROR]: [Protocolize] Protocolize 2.3.3:926
[15:14:47 ERROR]: [Protocolize] Stream Direction: UPSTREAM
[15:14:47 ERROR]: [Protocolize] Connection: [/127.0.0.1:65179|Hielke] <-> InitialHandler
[15:14:47 ERROR]: [Protocolize] Protocol version: 765
[15:14:47 ERROR]: io.netty.handler.codec.DecoderException: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.ClickWindow at protocol version 765 in direction TO_SERVER
[15:14:47 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[15:14:47 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[15:14:47 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[15:14:47 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:14:47 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:14:47 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[15:14:47 ERROR]: Caused by: net.md_5.bungee.protocol.BadPacketException: Protocolize is unable to read packet dev.simplix.protocolize.data.packets.ClickWindow at protocol version 765 in direction TO_SERVER
[15:14:47 ERROR]: Caused by: java.lang.ExceptionInInitializerError
[15:14:47 ERROR]:       at dev.simplix.protocolize.bungee.providers.BungeeCordComponentConverterProvider.platformConverter(BungeeCordComponentConverterProvider.java:29)
[15:14:47 ERROR]:       at dev.simplix.protocolize.api.chat.ChatElementImpl.ofJson(ChatElementImpl.java:24)
[15:14:47 ERROR]:       at dev.simplix.protocolize.api.chat.ChatElement.ofJson(ChatElement.java:20)
[15:14:47 ERROR]:       at dev.simplix.protocolize.api.item.ItemStackSerializer.read(ItemStackSerializer.java:66)
[15:14:47 ERROR]:       at dev.simplix.protocolize.data.packets.ClickWindow.read(ClickWindow.java:85)
[15:14:47 ERROR]:       at dev.simplix.protocolize.bungee.packet.BungeeCordProtocolizePacket.read(BungeeCordProtocolizePacket.java:55)
[15:14:47 ERROR]:       at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:534)
[15:14:47 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62)
[15:14:47 ERROR]:       at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13)
[15:14:47 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[15:14:47 ERROR]:       at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[15:14:47 ERROR]:       at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[15:14:47 ERROR]:       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[15:14:47 ERROR]:       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[15:14:47 ERROR]:       at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[15:14:47 ERROR]:       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[15:14:47 ERROR]:       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[15:14:47 ERROR]:       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[15:14:47 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[15:14:47 ERROR]: Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: italic
[15:14:47 ERROR]:       at dev.simplix.protocolize.bungee.providers.BungeeCordComponentConverterProvider$BungeeCordComponentConverter.<clinit>(BungeeCordComponentConverterProvider.java:41)
[15:14:47 ERROR]:       ... 38 more
[15:14:47 ERROR]: Caused by: java.lang.NoSuchFieldException: italic
[15:14:47 ERROR]:       at java.base/java.lang.Class.getDeclaredField(Class.java:2610)
[15:14:47 ERROR]:       at dev.simplix.protocolize.bungee.providers.BungeeCordComponentConverterProvider$BungeeCordComponentConverter.<clinit>(BungeeCordComponentConverterProvider.java:38)
[15:14:47 ERROR]:       ... 38 more```

**Comment by Exceptionflug** [comment]
Ah yes, this error is already fixed. You are running an outdated version of Protocolize. Please download it again from here: https://exceptionflug.de/protocolize
