### ISSUE TITLE
Unable obtain player

### ISSUE THREAD

**Issue by TymekSL** [Exceptionflug/protocolize#239]
java.lang.RuntimeException: Unable to obtain connection
at dev.simplix.protocolize.bungee.util.ReflectionUtil.getConnection(ReflectionUtil.java:91) ~[?:?]
at dev.simplix.protocolize.bungee.netty.ProtocolizeDecoderChannelHandler.<init>(ProtocolizeDecoderChannelHandler.java:41) ~[?:?]
at dev.simplix.protocolize.bungee.listener.PlayerListener.onServerSwitch(PlayerListener.java:52) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor98.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:511) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at net.md_5.bungee.ServerConnector.handleLogin(ServerConnector.java:247) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:851) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at net.md_5.bungee.protocol.packet.Login.handle(Login.java:294) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:140) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[FlameCord-1.9.6.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:731f10b:unknown]
at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.IllegalArgumentException: Can not set final net.md_5.bungee.UserConnection field net.md_5.bungee.connection.UpstreamBridge.con to net.md_5.bungee.connection.DownstreamBridge
at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:?]
at jdk.internal.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:?]
at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:?]
at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
at dev.simplix.protocolize.bungee.util.ReflectionUtil.getConnection(ReflectionUtil.java:88) ~[?:?]
... 42 more

**Comment by Exceptionflug** [comment]
Please follow the bug report template and fill in all required information
