### ISSUE TITLE
Pre 1.16 Shulker Boxes crash Players

### ISSUE THREAD

**Issue by J0schlZ** [Exceptionflug/protocolize#41]
**What behaviour is expected:**
Players to be able to use Shulker Boxes from 1.15.2.

**What behaviour is observed:**
If a player had a Shulker box with NBT data in an inventory [either theirs or in a chest] from 1.15.2, as soon as that inventory is loaded after the 1.16 upgrade the player will crash.

**Used Versions**
Bungeecord 1.16 Build: 1522
Protocolize v1.6.1

**Error:**
```
00:32:05 [WARNING] [IrgendSoEinTyp] <-> DownstreamBridge <-> [freebuild1] - bad packet ID, are mods in use!? Did not read all bytes from packet class de.exceptionflug.protocolize.items.packet.WindowItems 20 Protocol GAME Direction TO_CLIENT
00:32:05 [SEVERE] [Protocolize] Exception occurred when reading ItemStack from buffer. Protocol version = 736
java.lang.IllegalArgumentException: Tag type id 12 is unknown!
	at com.flowpowered.nbt.TagType.getById(TagType.java:103)
	at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:115)
	at com.flowpowered.nbt.stream.NBTInputStream.readTagPayload(NBTInputStream.java:200)
	at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:127)
	at com.flowpowered.nbt.stream.NBTInputStream.readTagPayload(NBTInputStream.java:200)
	at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:127)
	at com.flowpowered.nbt.stream.NBTInputStream.readTag(NBTInputStream.java:103)
	at de.exceptionflug.protocolize.items.ItemStack.readNBTTag(ItemStack.java:257)
	at de.exceptionflug.protocolize.items.ItemStack.read(ItemStack.java:207)
	at de.exceptionflug.protocolize.items.packet.SetSlot.read(SetSlot.java:71)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:33)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Exceptionflug** [comment]
Thank you for your interest,

I will fix this bug asap. It's caused by an outdated nbt library which I was using till now.

**Comment by J0schlZ** [comment]
Danke für die schnelle Antwort :)

**Comment by Exceptionflug** [comment]
Version 1.6.1 build 245 is now available which will fix this issue: https://github.com/Exceptionflug/protocolize/releases/tag/v1.6.1

Freut mich, dass ich helfen konnte :)
