### ISSUE TITLE
1.16 Villager Inventory

### ISSUE THREAD

**Issue by RealGatt** [Exceptionflug/protocolize#46]
Opening a Villager Inventory on a 1.16 Server causes this Protocolize Error in BungeeCord. The Inventory also does not open.

Using FlameCord 0.3.4, and MCCommons

```
[06:08:46] [ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[06:08:46] [ERROR]: [Protocolize] Stream: DOWNSTREAM
[06:08:46] [ERROR]: [Protocolize] Connection: Gatt
[06:08:46] [ERROR]: [Protocolize] Protocol version: 736
[06:08:46] [ERROR]: io.netty.handler.codec.DecoderException: java.lang.NullPointerException
[06:08:46] [ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:08:46] [ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:08:46] [ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[06:08:46] [ERROR]: at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:08:46] [ERROR]: at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[06:08:46] [ERROR]: at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[06:08:46] [ERROR]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[06:08:46] [ERROR]: at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[06:08:46] [ERROR]: at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[06:08:46] [ERROR]: at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[06:08:46] [ERROR]: at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[06:08:46] [ERROR]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[06:08:46] [ERROR]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[06:08:46] [ERROR]: at java.base/java.lang.Thread.run(Thread.java:831)
[06:08:46] [ERROR]: Caused by: java.lang.NullPointerException
[06:08:46] [ERROR]: at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:70)
[06:08:46] [ERROR]: at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:23)
[06:08:46] [ERROR]: at net.md_5.bungee.chat.TranslatableComponentSerializer.deserialize(TranslatableComponentSerializer.java:15)
[06:08:46] [ERROR]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[06:08:46] [ERROR]: at com.google.gson.Gson.fromJson(Gson.java:887)
[06:08:46] [ERROR]: at com.google.gson.Gson.fromJson(Gson.java:952)
[06:08:46] [ERROR]: at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
[06:08:46] [ERROR]: at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:77)
[06:08:46] [ERROR]: at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:20)
[06:08:46] [ERROR]: at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[06:08:46] [ERROR]: at com.google.gson.Gson.fromJson(Gson.java:887)
[06:08:46] [ERROR]: at com.google.gson.Gson.fromJson(Gson.java:952)
[06:08:46] [ERROR]: at com.google.gson.Gson.fromJson(Gson.java:925)
[06:08:46] [ERROR]: at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:46)
[06:08:46] [ERROR]: at de.exceptionflug.protocolize.inventory.packet.OpenWindow.read(OpenWindow.java:72)
[06:08:46] [ERROR]: at net.md_5.bungee.protocol.DefinedPacket.read0(DefinedPacket.java:217)
[06:08:46] [ERROR]: at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:57)
[06:08:46] [ERROR]: at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:14)
[06:08:46] [ERROR]: at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[06:08:46] [ERROR]: ... 26 more
```

**Comment by RealGatt** [comment]
Nevermind, issue is fixed with the latest build on the CI.
