### ISSUE TITLE
WindowItems OriginItemStack Error

### ISSUE THREAD

**Issue by MeowMiaoMiao** [Exceptionflug/protocolize#49]
bungeecord: 1.16.1-latest

Modify the ItemStack List of WindowItemsPacket. If one of the ItemStacks does not have Display or Lore. NPE exception will be thrown

[Protocolize] Exception occurred when writing ItemStack to buffer. Protocol version = 47
java.lang.NullPointerException
    at net.md_5.bungee.api.chat.BaseComponent.toLegacyText(BaseComponent.java:240)
    at de.exceptionflug.protocolize.items.ItemStack.write(ItemStack.java:160)
    at de.exceptionflug.protocolize.items.packet.WindowItems.write(WindowItems.java:66)
    at de.exceptionflug.protocolize.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:95)
    at de.exceptionflug.protocolize.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:25)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:748)

**Comment by Exceptionflug** [comment]
Hey,

thank you for reporting. This issue have been resolved now, Just download the latest build from Jenkins: https://ci.exceptionflug.de/job/Protocolize/

**Comment by MeowMiaoMiao** [comment]
> Hey,
> 
> thank you for reporting. This issue have been resolved now, Just download the latest build from Jenkins: https://ci.exceptionflug.de/job/Protocolize/

It seems that some ItemStacks will not be displayed in the inventory
Potion, pickaxe with insufficient durability...

original
![QQ截图20200801171549](https://user-images.githubusercontent.com/29674595/89098554-40b19d00-d3d8-11ea-8281-ed6d25829470.jpg)
modified
![QQ截图20200801171538](https://user-images.githubusercontent.com/29674595/89098556-43ac8d80-d3d8-11ea-9344-8f1a80649e68.jpg)

**Comment by Exceptionflug** [comment]
Could you please send the code used to create those items? I guess there is something wrong with the durability.

**Comment by MeowMiaoMiao** [comment]
> Could you please send the code used to create those items? I guess there is something wrong with the durability.

`    //TODO BUG
    private boolean tranItemStack(ProxiedPlayer player, ItemStack itemStack) {
        // System.out.println(itemStack);
        if (itemStack == ItemStack.NO_DATA) {
            return false;
        }
        boolean modfiy = false;
        if (itemStack.getDisplayNameComponents() != null) {
            for (BaseComponent baseComponents : itemStack.getDisplayNameComponents()) {
                if (baseComponents instanceof TextComponent) {
                    String display = defaultTran(player, ((TextComponent) baseComponents).getText());
                    if (display != null) {
                        ((TextComponent) baseComponents).setText(display);
                        modfiy = true;
                    }
                }
            }
        }
        if (itemStack.getLoreComponents() != null) {
            for (BaseComponent[] baseComponents : itemStack.getLoreComponents()) {
                for (BaseComponent baseComponent : baseComponents) {
                    if (baseComponent instanceof TextComponent) {
                        String s1 = defaultTran(player, ((TextComponent) baseComponent).getText());
                        if (s1 != null) {
                            ((TextComponent) baseComponent).setText(s1);
                            modfiy = true;
                        }
                    }
                }
            }
        }
        return modfiy;
    }`

`    @Override
    public ParseResult<WindowItems> tran(Stream stream, WindowItems packet, ProxiedPlayer player) {
        boolean modify = false;
        for (ItemStack item : packet.getItems()) {
            if (item != null) {
                if (tranItemStack(player, item)) {
                    modify = true;
                }
            }
        }
        if (modify) {
            return new ParseResult<>(packet, true, false);
        }
        return (ParseResult<WindowItems>) NO_MODIFY;
    }`
`        PacketAdapter<T> downStreamAdapter = new PacketAdapter<T>(Stream.DOWNSTREAM, clazz, (byte) 64) {
            public void receive(PacketReceiveEvent<T> event) {
                ProxiedPlayer player = event.getPlayer();

                PacketParseAdapter.ParseResult<T> translate = packetParseAdapter.parse(Stream.DOWNSTREAM, event.getPacket(), player);
                if (translate.isModify()) {
                    event.setPacket(translate.getPacket());
                    event.markForRewrite();
                }
            }
        };`

**Comment by MeowMiaoMiao** [comment]
I just modified the display and lore...

**Comment by Exceptionflug** [comment]
I will take a look at that when I'm back home next week. Could you please tell me your client and server version?

**Comment by MeowMiaoMiao** [comment]
> I will take a look at that when I'm back home next week. Could you please tell me your client and server version?

server:spigot 1.8.8 
client: 1.8.9

**Comment by Exceptionflug** [comment]
Don't set directly the text via setText to the components. Use `TextComponent.fromLegacyText()` to create a component array from a string. And `TextComponent.toLegacyText()` to get a String from a component array.

**Comment by MeowMiaoMiao** [comment]
> Don't set directly the text via setText to the components. Use `TextComponent.fromLegacyText()` to create a component array from a string. And `TextComponent.toLegacyText()` to get a String from a component array.

Doesn't seem to solve the problem

**Comment by MeowMiaoMiao** [comment]
Can I fix this durability problem? I need it. Thank you~

**Comment by Exceptionflug** [comment]
Please publish your source code on a private GitHub repository and add me so I can figure out whats wrong there.

**Comment by MeowMiaoMiao** [comment]
> Please publish your source code on a private GitHub repository and add me so I can figure out whats wrong there.

Just modify the ItemStack displayname in the WindowItems package to reproduce
```
    @Override
    public void onEnable() {
        // Plugin startup logic
        PacketAdapter<WindowItems> adapter = new PacketAdapter<WindowItems>(Stream.DOWNSTREAM, WindowItems.class, (byte) 64) {
            public void receive(PacketReceiveEvent<WindowItems> event) {
                for (ItemStack item : event.getPacket().getItems()) {
                  //     item.setDisplayName("display");
                    item.setDisplayName(new TextComponent("display"));
                }
                event.markForRewrite();
            }
        };
        ProtocolAPI.getEventManager().registerListener(adapter);
    }
```

**Comment by MeowMiaoMiao** [comment]
After modifying ItemStack all durability item will be invisible (air)

**Comment by Exceptionflug** [comment]
This seems to be a bug which was introduced in the first version of Protocolize. If the durability of an legacy (MC < 1.13) item is not equal to the defined mapping durability (default 0), Protocolize returns ItemType `null` when reading the ItemStack. This causes the loss of the item when rewriting the packet data since Protocolize doesn't know which type the item has. I am currently working on a fix for this.

**Comment by Exceptionflug** [comment]
Please download and test latest release 1.6.3

**Comment by MeowMiaoMiao** [comment]
> Please download and test latest release 1.6.3
ok,thank u!
