### ISSUE TITLE
EXCEPTION CAUGHT IN DECODER

### ISSUE THREAD

**Issue by MrArtem1337** [Exceptionflug/protocolize#58]
[00:00:30] [Netty Worker IO Thread #0/ERROR]: [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
[00:00:30] [Netty Worker IO Thread #0/ERROR]: [Protocolize] Stream: DOWNSTREAM
[00:00:30] [Netty Worker IO Thread #0/ERROR]: [Protocolize] Connection: sans_killer_754
[00:00:30] [Netty Worker IO Thread #0/ERROR]: [Protocolize] Protocol version: 335
[00:00:30] [Netty Worker IO Thread #0/WARN]: java.lang.NoSuchMethodError: de.exceptionflug.protocolize.items.AbstractCustomItemIDMapping.isApplicable(Lde/exceptionflug/protocolize/items/ItemStack;IIS)Z
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at de.exceptionflug.protocolize.items.ItemType.getType(ItemType.proto:42)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at de.exceptionflug.protocolize.items.ItemStack.read(ItemStack.java:251)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at de.exceptionflug.protocolize.items.packet.WindowItems.read(WindowItems.java:77)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:49)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:11)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[00:00:30] [Netty Worker IO Thread #0/WARN]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by Exceptionflug** [comment]
Hey,

this issue has already been resolved. Please download the latest version of protocolize from our CI server: https://ci.exceptionflug.de/
