### ISSUE TITLE
i dont know why this is happening then i use Flamecord

### ISSUE THREAD

**Issue by ItsVollx** [Exceptionflug/protocolize#85]
05.07 17:00:07 [Multicraft] Server already running
05.07 17:00:07 [Server] INFO 2021-07-05 17:00:07,301 main WARN Advanced terminal features are not available in this environment
05.07 17:00:07 [Server] INFO Using mbed TLS based native cipher.
05.07 17:00:07 [Server] INFO Using zlib based native compressor.
05.07 17:00:07 [Server] INFO Enabled FlameCord version 0.5.9
05.07 17:00:07 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
05.07 17:00:07 [Server] INFO Epoll is working, utilising it!
05.07 17:00:07 [Server] INFO Loaded plugin ViaVersion version 4.0.1-SNAPSHOT by _MylesC, creeper123123321, Gerrygames, KennyTV, Matsv
05.07 17:00:07 [Server] INFO Loaded plugin ViaRewind version 2.0.1-SNAPSHOT by Gerrygames
05.07 17:00:07 [Server] INFO Loaded plugin Geyser-BungeeCord version 1.4.0-SNAPSHOT by GeyserMC
05.07 17:00:07 [Server] INFO Loaded plugin MiniMOTD version 2.0.3 by jmp
05.07 17:00:07 [Server] WARN Error loading plugin ViaRewind-Legacy-Support
05.07 17:00:07 [Server] INFO java.lang.NoClassDefFoundError: org/bukkit/plugin/java/JavaPlugin
05.07 17:00:07 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
05.07 17:00:07 [Server] INFO at java.lang.ClassLoader.defineClass(ClassLoader.java:1010) ~[?:?]
05.07 17:00:07 [Server] INFO at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:146) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:435) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:341) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO Caused by: java.lang.ClassNotFoundException: org.bukkit.plugin.java.JavaPlugin
05.07 17:00:07 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[FlameCord.jar:git:FlameCord-Bootstrap:1.17-R0.1-SNAPSHOT:5f92ed2:unknown]
05.07 17:00:07 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
05.07 17:00:07 [Server] INFO ... 13 more
05.07 17:00:08 [Server] INFO Loaded plugin LuckPerms version 5.3.48 by Luck
05.07 17:00:08 [Server] INFO Loaded plugin BotSentry version 9.0.2-THANATOS by New Era Studios & Lahuca Software Development
05.07 17:00:08 [Server] INFO Loaded plugin ViaBackwards version 4.0.1-SNAPSHOT by Matsv, KennyTV, Gerrygames, creeper123123321, ForceUpdate1
05.07 17:00:08 [Server] INFO Loaded plugin BungeeTabListPlus version 3.4.3 by

**Comment by ItsVollx** [comment]
then I use bungee cords I don't get these issues

**Comment by ItsVollx** [comment]
then I use bungee cords I don't get these issues
