### ISSUE TITLE
 [Protocolize] Exception occurred when reading ItemStack from buffer. Protocol version = 756

### ISSUE THREAD

**Issue by Galajus** [Exceptionflug/protocolize#86]
**Describe the bug**
Who know what happend :d

**To Reproduce**
This happend allways when i click outside of inventory

**Expected behavior**
```
> 02:43:57 [WARNING] [Protocolize] Packet de.exceptionflug.protocolize.items.packet.WindowItems was not read successfully. Please look into protocolize.log for further details.

19:29:59 [SEVERE] [Protocolize] Exception occurred when reading ItemStack from buffer. Protocol version = 756
java.lang.IndexOutOfBoundsException: readerIndex(9) + length(1) exceeds writerIndex(9): UnpooledSlicedByteBuf(ridx: 9, widx: 9, cap: 9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 11, widx: 11, cap: 11))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:732)
	at io.netty.buffer.AbstractByteBuf.readBoolean(AbstractByteBuf.java:741)
	at de.exceptionflug.protocolize.items.ItemStack.read(ItemStack.java:61)
	at de.exceptionflug.protocolize.inventory.packet.ClickWindow.read(ClickWindow.java:86)
	at net.md_5.bungee.protocol.DefinedPacket.read0(DefinedPacket.java:166)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:90)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:19)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:831)
```

And i have many this info. in protocolize.log (binary is changing):
```
Jul 10, 2021, 7:29:55 PM | Direction = TO_CLIENT | Version = 756 | Packet = de.exceptionflug.protocolize.items.packet.WindowItems (20) | Packet has 1 trailing bytes left
01 01 27 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01 8f 01 40 00 00 00 00 00 00 00 
```

**Proxy environment**
Bungee: Aegis 9.2.1

Plugins:
- CMIB
- DynamicBungeeAuth
- ForceResourcePack
- Geyser BuungeeCord
- PL-Hide-Pro
- protocolize (1.7.1)

**Minecraft versions used**
Server: Purpur 1.17.1 buid 1260
i'm using vi version and viabackwards

Java 16

**Comment by KotlinFactory** [comment]
Hey, please update to the latest Waterfall/BungeeCord and tell us whether this is still happening.

**Comment by Galajus** [comment]
I'm using latest version of Aegis (9.2.1)

**Comment by KotlinFactory** [comment]
Then use the latest version of Waterfall please.

**Comment by ham1255** [comment]
this was fixed in last commit but author didn't release update on spigot

**Comment by Exceptionflug** [comment]
Small bugfixes are never posted as updates since there is no version number increase and the download link on spigotmc.org points always to the latest build.
