### ISSUE TITLE
NoClassDefFoundError: de/exceptionflug/protocolize/api/handler/PacketListener

### ISSUE THREAD

**Issue by MHProDev** [Exceptionflug/protocolize#88]
```
java.lang.NoClassDefFoundError: de/exceptionflug/protocolize/api/handler/PacketListener
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:1.8.0_292]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) ~[?:1.8.0_292]
	at java.lang.Class.getConstructor0(Class.java:3075) ~[?:1.8.0_292]
	at java.lang.Class.getDeclaredConstructor(Class.java:2178) ~[?:1.8.0_292]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:395) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:300) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
Caused by: java.lang.ClassNotFoundException: de.exceptionflug.protocolize.api.handler.PacketListener
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:97) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall-1.17-448.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_292]
```
Waterfall version git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:93773f9:448
java: corretto-1.8.0_292
maven: 

```
    <repositories>
        <repository>
            <id>sonatype</id>
            <url>https://oss.sonatype.org/content/groups/public/</url>
        </repository>
        <repository>
            <id>exceptionflug</id>
            <url>https://mvn.exceptionflug.de/repository/exceptionflug-public/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>net.md-5</groupId>
            <artifactId>bungeecord-api</artifactId>
            <version>1.17-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>de.exceptionflug</groupId>
            <artifactId>protocolize-api</artifactId>
            <version>1.7.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>de.exceptionflug</groupId>
            <artifactId>protocolize-items</artifactId>
            <version>1.7.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>de.exceptionflug</groupId>
            <artifactId>protocolize-inventory</artifactId>
            <version>1.7.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>de.exceptionflug</groupId>
            <artifactId>protocolize-world</artifactId>
            <version>1.7.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>io.github.waterfallmc</groupId>
            <artifactId>waterfall-api</artifactId>
            <version>1.17-R0.1-SNAPSHOT</version>
        </dependency>

    </dependencies>
```

**Comment by MHProDev** [comment]
protocolize version: 1.7.1-SNAPSHOT:646

**Comment by KotlinFactory** [comment]
Hey MHProDev,

Stop shading protocolize into your jar & install protocolize-plugin on your server.

Regards

**Comment by MHProDev** [comment]
![image](https://user-images.githubusercontent.com/63018646/126879361-e048c923-be63-4b39-bef3-cbc5ee9e6906.png)

**Comment by MHProDev** [comment]
[19:26:23 INFO]: ======= PROTOCOLIZE =======
[19:26:23 INFO]: Version 1.7.1-SNAPSHOT:646 by Exceptionflug
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.ChangeGameState
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.NamedSoundEffect
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.SignUpdate
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerPosition
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerLook
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.PlayerPositionLook
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.world.packet.SignUpdate
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.SetSlot
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.WindowItems
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.HeldItemChange
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.UseItem
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.BlockPlacement
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.items.packet.HeldItemChange
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.OpenWindow
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.CloseWindow
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ConfirmTransaction
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.WindowProperty
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.CloseWindow
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ConfirmTransaction
[19:26:23 INFO]: [Protocolize] Injected custom packet: de.exceptionflug.protocolize.inventory.packet.ClickWindow
[19:26:23 INFO]: Enabled plugin protocolize-plugin version 1.7.1-SNAPSHOT:646 by Exceptionflug
