### ISSUE TITLE
"de.exceptionflug.protocolize.inventory.InventoryType.getLegacyTypeId(int)" because "this.inventoryType" is null

### ISSUE THREAD

**Issue by MeowRay** [Exceptionflug/protocolize#90]
plugin-version: 1.7.1-latest
bungeecord-version: 1.17.1-latest
```
12:36:12 [严重] [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
12:36:12 [严重] [Protocolize] Stream: DOWNSTREAM
12:36:12 [严重] [Protocolize] Connection: 1231231230
12:36:12 [严重] [Protocolize] Protocol version: 47
12:36:12 [严重] io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "de.exceptionflug.protocolize.inventory.InventoryType.getLegacyTypeId(int)" because "this.inventoryType" is null

12:36:12 [严重]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)

12:36:12 [严重]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

12:36:12 [严重]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)

12:36:12 [严重]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)

12:36:12 [严重]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)

12:36:12 [严重]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

12:36:12 [严重]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

12:36:12 [严重]     at java.base/java.lang.Thread.run(Thread.java:831)

12:36:12 [严重] Caused by: java.lang.NullPointerException: Cannot invoke "de.exceptionflug.protocolize.inventory.InventoryType.getLegacyTypeId(int)" because "this.inventoryType" is null

12:36:12 [严重]     at de.exceptionflug.protocolize.inventory.packet.OpenWindow.write(OpenWindow.java:95)

12:36:12 [严重]     at de.exceptionflug.protocolize.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:101)

12:36:12 [严重]     at de.exceptionflug.protocolize.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:27)

12:36:12 [严重]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)

12:36:12 [严重]     ... 26 more

12:36:12 [严重] [Protocolize] === EXCEPTION CAUGHT IN DECODER ===
12:36:12 [严重] [Protocolize] Stream: DOWNSTREAM
12:36:12 [严重] [Protocolize] Connection: 1231231230
12:36:12 [严重] [Protocolize] Protocol version: 47
12:36:12 [严重] io.netty.handler.codec.DecoderException: java.lang.NullPointerException: Cannot invoke "de.exceptionflug.protocolize.inventory.InventoryType.getLegacyTypeId(int)" because "this.inventoryType" is null

12:36:12 [严重]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)

12:36:12 [严重]     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)

12:36:12 [严重]     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)

12:36:12 [严重]     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)

12:36:12 [严重]     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)

12:36:12 [严重]     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)

12:36:12 [严重]     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)

12:36:12 [严重]     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)

12:36:12 [严重]     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

12:36:12 [严重]     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

12:36:12 [严重]     at java.base/java.lang.Thread.run(Thread.java:831)

12:36:12 [严重] Caused by: java.lang.NullPointerException: Cannot invoke "de.exceptionflug.protocolize.inventory.InventoryType.getLegacyTypeId(int)" because "this.inventoryType" is null

12:36:12 [严重]     at de.exceptionflug.protocolize.inventory.packet.OpenWindow.write(OpenWindow.java:95)

12:36:12 [严重]     at de.exceptionflug.protocolize.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:101)

12:36:12 [严重]     at de.exceptionflug.protocolize.netty.ProtocolizeDecoderChannelHandler.decode(ProtocolizeDecoderChannelHandler.java:27)

12:36:12 [严重]     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)

12:36:12 [严重]     ... 26 more
```

**Comment by Exceptionflug** [comment]
Not longer supported. Please upgrade to v2.
